import { IPosition } from './interfaces';

export const jobs: IPosition[] = [
	{
		company: 'RIESTER',
		position: 'Web Developer',
		startDate: '2020-02-28',
		endDate: '2023-10-31',
		highlights: [
			'Led collaborations between departments to create visually appealing, user-friendly websites.',
			'Advocated for accessible designs that cater to diverse audiences.',
			'Enabled smooth collaboration between local and remote developers using <b>Git</b> and <b>Bitbucket</b> for efficient teamwork.',
			'Innovated by crafting a custom plugin that enabled more brand consistency by integrating the <b>Bootstrap</b> system more seemlessly into the visual editor and the WordPres core.',
			'Offered thorough documentation and training for teams and clients to better utilize developed systems.',
			'Led website development across various industries and platforms, such as <b>WordPress</b>, <b>Kentico</b>, <b>Umbraco</b>, and <b>Shopify</b>, showcasing versatility and adaptability in meeting client needs.',
		],
		summary:
			'Primarily works with PHP, JavaScript, HTML, CSS, and Wordpress to develop full-featured websites and applications',
		url: 'https://www.riester.com',
		location: {
			countryCode: 'US',
			city: 'Phoenix',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'REV77',
		position: 'Web Developer',
		startDate: '2019-11-30',
		endDate: '2020-02-28',
		highlights: [
			'Collaborated on managing an extensive workload, addressing an overflow of website edits effectively and efficiently.',
			'Upheld and enhanced website performance, consistently implementing improvements to elevate functionality and user engagement.',
			'Enhanced <b>WordPress</b> websites utilizing a personalized visual composer builder, ensuring up-to-date and visually captivating online platforms.',
			'Engaged in collaborative efforts to strategize and execute effective marketing strategies.',
		],
		summary: '',
		url: 'https://www.rev77.com/',
		location: {
			countryCode: 'US',
			city: 'Tempe',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'MAAT Legal ',
		position: 'Web Developer / IT Manager / Graphic Designer',
		startDate: '2018-09-30',
		endDate: '2019-11-30',
		highlights: [
			'Restructured IT infrastructure by introducing GSuite and 1Password, providing extensive employee training for a smooth transition to the new systems.',
			'Led a complete rebranding for Dana & Associates, modernizing both print and digital materials to create a unified brand image.',
			'Achieved a 200% increase in conversions on danalegalhelp.com by developing a more user-friendly, responsive <b>WordPress</b> website using <b>Bootstrap</b> 4.',
			'Ensured brand consistency by designing various print materials to match the new brand identity and website design for Dana & Associates.',
		],
		summary: '',
		url: 'https://maatlegal.com/',
		location: {
			countryCode: 'US',
			city: 'Mesa',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'Blufish Design',
		position: 'Web Developer - Contract',
		startDate: '2018-05-31',
		endDate: '2018-06-30',
		highlights: [
			'Expertly managed and supported the handling of excess website edits, ensuring a smooth and efficient workflow during high-demand periods.',
			'Crafted responsive <b>HTML</b> emails utilizing Litmus, ensuring compatibility across various email clients and delivering visually appealing, effective communication.',
			'Seamlessly incorporated requested features into <b>Shopify</b> websites, enhancing their functionality and meeting client specifications with precision.',
		],
		summary: '',
		url: 'https://blufish.com/',
		location: {
			countryCode: 'US',
			city: 'Tempe',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'Skyhook Interactive',
		position: 'Web Developer',
		startDate: '2017-11-30',
		endDate: '2018-03-31',
		highlights: [
			'Collaborated in a developer team, using <b>Git</b> and <b>Bitbucket</b> for efficient simultaneous editing and management of existing sites, ensuring a smooth workflow.',
			'Partnered with a developer to create ADA-compliant <b>HTML</b> landing pages for Monster.com, meeting accessibility standards and improving user experience.',
			'Led the development of a detailed <b>WordPress</b> eCommerce site using <b>WooCommerce</b>, precisely aligning it with Sketch files and integrating a custom search function.',
			'Designed a custom <b>Shopify</b> theme that perfectly matched specific <b>Photoshop</b> designs, ensuring an aesthetically pleasing and functional online platform.',
		],
		summary: '',
		url: 'https://skyhookinteractive.com/',
		location: {
			countryCode: 'US',
			city: 'Mesa',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'Joybyte',
		position: 'Senior Web Developer',
		startDate: '2014-06-30',
		endDate: '2017-11-30',
		highlights: [
			'Led three years of transforming <b>Photoshop</b> files into pixel-perfect, responsive websites for major clients.',
			'Established standards and trained junior developers for consistent web development.',
			'Introduced a <b>WordPress</b> site manager, saving time and costs managing 150+ clients.',
			'Engineered a custom page builder using Advanced Custom Fields for uniform site quality among different developers.',
			'Collaborated with other department heads to improve workflow and integration between departments.',
		],
		summary: '',
		url: 'https://www.joybyte.com/',
		location: {
			countryCode: 'US',
			city: 'Scottsdale',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'University of Advancing Technology',
		position: 'Web Administrator',
		startDate: '2013-06-30',
		endDate: '2014-06-30',
		highlights: [
			'Updated multiple micro-sites to meet modern website standards, ensuring consistency and relevance across the platform.',
			'Created a user-friendly and engaging <b>WordPress</b> blog customized for the student leadership group.',
			'Collaborated with backend developers to improve user interface (UI) for their applications, enhancing visual appeal and ease of use.',
			'Developed responsive HTML emails using Green Rope, combining design and coding skills for effective communication.',
		],
		summary: '',
		url: 'https://www.uat.edu/',
		location: {
			countryCode: 'US',
			city: 'Phoenix',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'ASU Decision Theater Network',
		position: 'Web Developer',
		startDate: '2012-12-31',
		endDate: '2013-06-30',
		highlights: [
			'Developed a unique <b>WordPress</b> theme with custom post types and taxonomies, using SASS and Compass for efficient development.',
			'Set up Google Analytics for comprehensive data tracking, optimizing site performance and user engagement.',
			'Introduced a team wiki to enhance collaboration and knowledge sharing among team members, improving overall productivity.',
			'Collaborated with an ASU professor to create impactful, concise single-page handouts for two external projects, showcasing effective collaboration and visual communication skills.',
		],
		summary: '',
		url: 'https://dt.asu.edu/',
		location: {
			countryCode: 'US',
			city: 'Tempe',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'ASU Foundation',
		position: 'Web Design Intern',
		startDate: '2010-06-30',
		endDate: '2012-11-30',
		highlights: [
			'Created various promotional videos using Final Cut Pro, enhancing visual storytelling for different departments.',
			'Designed engaging internal emails using <b>Photoshop</b> and <b>Illustrator</b> for professional communication.',
			'Developed <b>HTML</b> emails for internal and external use, ensuring consistency in communication across platforms.',
			'Managed diverse tasks across multiple Foundation websites, showcasing adaptability in web development.',
			'Built three unique microsites for different departments, providing tailored online solutions for specific organizational needs.',
		],
		summary: '',
		url: 'https://www.asufoundation.org/',
		location: {
			countryCode: 'US',
			city: 'Tempe',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
];
