import { IPosition } from './interfaces';

export const jobs: IPosition[] = [
	{
		company: 'RIESTER',
		position: 'Web Developer',
		startDate: '2020-02-28',
		endDate: '2023-10-31',
		highlights: [
			'Led collaborations between departments to create visually appealing, user-friendly websites.',
			'Advocated for accessible designs that cater to diverse audiences.',
			'Enabled smooth collaboration between local and remote developers using <b>Git</b> and <b>Bitbucket</b> for efficient teamwork.',
			'Innovated by crafting a custom plugin that enabled more brand consistency by integrating the <b>Bootstrap</b> system more seemlessly into the visual editor and the WordPres core.',
			'Offered thorough documentation and training for teams and clients to better utilize developed systems.',
			'Led website development across various industries and platforms, such as <b>WordPress</b>, <b>Kentico</b>, <b>Umbraco</b>, and <b>Shopify</b>, showcasing versatility and adaptability in meeting client needs.',
		],
		summary:
			'Primarily works with PHP, JavaScript, HTML, CSS, and Wordpress to develop full-featured websites and applications',
		url: 'https://www.riester.com',
		location: {
			countryCode: 'US',
			city: 'Phoenix',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'REV77',
		position: 'Web Developer',
		startDate: '2019-11-30',
		endDate: '2020-02-28',
		highlights: [
			'Collaborated on managing an extensive workload, addressing an overflow of website edits effectively and efficiently.',
			'Upheld and enhanced website performance, consistently implementing improvements to elevate functionality and user engagement.',
			'Enhanced <b>WordPress</b> websites utilizing a personalized visual composer builder, ensuring up-to-date and visually captivating online platforms.',
			'Engaged in collaborative efforts to strategize and execute effective marketing strategies, contributing valuable insights for comprehensive online presence and outreach.',
		],
		summary: '',
		url: 'https://www.rev77.com/',
		location: {
			countryCode: 'US',
			city: 'Tempe',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'MAAT Legal ',
		position: 'Web Developer / IT Manager / Graphic Designer',
		startDate: '2018-09-30',
		endDate: '2019-11-30',
		highlights: [
			'Orchestrated a comprehensive restructuring of the IT infrastructure by implementing GSuite and 1Password, and conducted extensive training sessions for all employees, ensuring a seamless transition and optimal utilization of the new systems.',
			"Spearheaded a full-scale rebranding initiative for Dana & Associates, overseeing a complete overhaul of both print and digital materials, thereby modernizing and unifying the brand's image.",
			'Drastically boosted conversions by 200% on danalegalhelp.com through the creation of a more intuitive, responsive <b>WordPress</b> website based on the robust <b>Bootstrap</b> 4 framework, enhancing user experience and engagement.',
			'Maintained brand coherence across various mediums by designing a multitude of print materials, such as business cards, brochures, mailing labels, and various documents, harmonizing them with the new brand identity and website design',
		],
		summary: '',
		url: 'https://maatlegal.com/',
		location: {
			countryCode: 'US',
			city: 'Mesa',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'Blufish Design',
		position: 'Web Developer - Contract',
		startDate: '2018-05-31',
		endDate: '2018-06-30',
		highlights: [
			'Expertly managed and supported the handling of excess website edits, ensuring a smooth and efficient workflow during high-demand periods.',
			'Crafted responsive <b>HTML</b> emails utilizing Litmus, ensuring compatibility across various email clients and delivering visually appealing, effective communication.',
			'Seamlessly incorporated requested features into <b>Shopify</b> websites, enhancing their functionality and meeting client specifications with precision.',
		],
		summary: '',
		url: 'https://blufish.com/',
		location: {
			countryCode: 'US',
			city: 'Tempe',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'Skyhook Interactive',
		position: 'Web Developer',
		startDate: '2017-11-30',
		endDate: '2018-03-31',
		highlights: [
			'Collaborated effectively within a team of developers, utilizing <b>Git</b> and <b>Bitbucket</b> for concurrent management and editing of existing sites, ensuring a streamlined and organized workflow.',
			'Teamed up with another developer to produce custom ADA-compliant <b>HTML</b>  landing pages for Monster.com, meeting accessibility standards and optimizing user experience.',
			'Orchestrated the development of a comprehensive <b>WordPress</b>-based eCommerce site using <b>WooCommerce</b>, aligning it precisely with Sketch files. This included the integration of a custom search function and the utilization of Bootstrap 3 for framework support.',
			'Engineered a tailor-made <b>Shopify</b> theme to match precise Photoshop designs, ensuring a seamless translation of visual concepts into a functional and aesthetically pleasing online platform.',
		],
		summary: '',
		url: 'https://skyhookinteractive.com/',
		location: {
			countryCode: 'US',
			city: 'Mesa',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'Joybyte',
		position: 'Senior Web Developer',
		startDate: '2014-06-30',
		endDate: '2017-11-30',
		highlights: [
			'Independently spearheaded the development of intricate websites for major clients over a three-year period, showcasing consistent high-quality output.',
			'Established departmental standards and methodologies, providing guidance and training to junior developers in creating custom themes and templates, ensuring a cohesive approach to web development.',
			'Implemented a <b>WordPress</b> site manager, optimizing the management of 150+ clients across various departments, resulting in significant time and cost savings for the company.',
			'Engineered a custom page builder using Advanced Custom Fields to maintain uniform site quality across multiple developers, ensuring consistency in the final output regardless of the creator.',
			'Collaborated with department heads to streamline integration between design, account management, and web development, fostering a more efficient and collaborative workflow across various facets of the company.',
		],
		summary: '',
		url: 'https://www.joybyte.com/',
		location: {
			countryCode: 'US',
			city: 'Scottsdale',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'University of Advancing Technology',
		position: 'Web Administrator',
		startDate: '2013-06-30',
		endDate: '2014-06-30',
		highlights: [
			'Modernized numerous micro-sites to align with current website standards, ensuring consistency and relevance across the online platform.',
			'Engineered a responsive <b>WordPress</b> blog specifically tailored for the student leadership group, emphasizing usability and engaging design.',
			'Collaborated with back-end developers to enhance user interface (UI) for their applications, contributing to a more intuitive and visually appealing end product.',
			'Crafted responsive HTML emails using Green Rope, combining design and coding expertise to create visually engaging and functional email communications.',
		],
		summary: '',
		url: 'https://www.uat.edu/',
		location: {
			countryCode: 'US',
			city: 'Phoenix',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'ASU Decision Theater Network',
		position: 'Web Developer',
		startDate: '2012-12-31',
		endDate: '2013-06-30',
		highlights: [
			'Engineered a bespoke <b>WordPress</b> theme incorporating custom post types and taxonomies, utilizing <b>SASS</b> and Compass for streamlined and efficient development.',
			'Established Google Analytics for the site, enabling comprehensive data tracking and analysis to optimize performance and user engagement.',
			'Instituted a team wiki to foster improved collaboration and knowledge sharing among team members, enhancing overall productivity and workflow efficiency.',
			'Collaborated with a professor from ASU to design and produce a concise, impactful single-page handout for two external projects, demonstrating effective collaboration and visual communication skills.',
		],
		summary: '',
		url: 'https://dt.asu.edu/',
		location: {
			countryCode: 'US',
			city: 'Tempe',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
	{
		company: 'ASU Foundation',
		position: 'Web Design Intern',
		startDate: '2010-06-30',
		endDate: '2012-11-30',
		highlights: [
			'Produced multiple promotional videos utilizing Final Cut Pro for diverse departments, enhancing visual storytelling and promotional content.',
			'Crafted visually compelling internal emails using Photoshop and Illustrator, ensuring an engaging and professional communication format.',
			'Developed <b>HTML</b> emails for both internal and external distribution, ensuring consistent and effective communication across platforms.',
			'Successfully executed diverse tasks across multiple websites managed by the Foundation, showcasing versatility and adaptability in handling varied web development responsibilities.',
			'Engineered three distinct microsites for different departments, demonstrating proficiency in delivering tailored online solutions for specific organizational needs.',
		],
		summary: '',
		url: 'https://www.asufoundation.org/',
		location: {
			countryCode: 'US',
			city: 'Tempe',
			locality: 'Arizona',
			localityCode: 'AZ',
		},
	},
];
